// edison: the temporary database for storing the book details 
export const Bookdata = [
  {
    bookno: "1",
    name: "Software engineering",
    author: "Ian Sommerville",
    publisher: "Pearson",
    year: "2015",
    price: "49.99",
    ISBN13: "978-0133943030",
    details:
      "Software Engineering introduces readers to the overwhelmingly important subject of software programming and development. In the past few years, computer systems have come to dominate not just our technological growth, but the foundations of our world’s major industries. This text seeks to lay out the fundamental concepts of this huge and continually growing subject area in a clear and comprehensive manner.",
    img: "/assets/book1.jpg",
  },
  {
    bookno: "2",
    name: "UML @ classroom: an introduction to object-oriented modeling",
    author: "Martina Seidl",
    publisher: "Springer",
    year: "2015",
    price: "24.99",
    ISBN13: "978-3319127415",
    details:
      "This textbook mainly addresses beginners and readers with a basic knowledge of object-oriented programming languages like Java or C#, but with little or no modeling or software engineering experience – thus reflecting the majority of students in introductory courses at universities. Using UML, it introduces basic modeling concepts in a highly precise manner, while refraining from the interpretation of rare special cases.",
    img: "/assets/book2.jpg",
  },
  {
    bookno: "3",
    name: "Interaction design: beyond human-computer interaction",
    author: "Helen Sharp; Jenny Preece; Yvonne Rogers",
    publisher: "Wiley",
    year: "2019",
    price: "27.99",
    ISBN13: "978-1119547259",
    details:
      "Interaction design is about designing interactive digital products to support the way people communicate and interact in their everyday and working lives. To be successful, interaction designers need a mixed set of skills drawn from human–computer interaction, web design, psychology, computer science, information systems, data science and the human sciences as well as an understanding of the desires and needs of people and the kinds of technology available.",
    img: "/assets/book3.jpg",
  },
  {
    bookno: "4",
    name: "Interaction design: beyond human-computer interaction (old edition)",
    author: "Helen Sharp; Jenny Preece; Yvonne Rogers",
    publisher: "John Wiley & Sons",
    year: "2007",
    price: "15.99",
    ISBN13: " 978-0470018668",
    details:
      "A lively and highly interactive Web site that will enable students to collaborate on experiments, compete in design competitions, collaborate on designs, find resources and communicate with others",
    img: "/assets/book4.jpg",
  },
  {
    bookno: "5",
    name: "The design of everyday things",
    author: "Donald A. Norman",
    publisher: "MIT Press",
    year: "2013",
    price: "12.85",
    ISBN13: "978-0262525671",
    details:
      "Even the smartest among us can feel inept as we try to figure out the shower control in a hotel or attempt to navigate an unfamiliar television set or stove. ",
    img: "/assets/book5.jpg",
  },
  {
    bookno: "6",
    name: "How to solve it: modern heuristics",
    author: "Zbigniew Michalewicz; David B. Fogel",
    publisher: "Springer Berlin Heidelberg",
    year: "2004",
    price: "10.55",
    ISBN13: "978-3642061349",
    details:
      "It's heartening to know that so many people appreciated the book and, even more importantly, were using the book to help them solve their problems. ",
    img: "/assets/book6.jpg",
  },
  {
    bookno: "7",
    name: "Swarm intelligence: from natural to artificial systems",
    author: "Eric Bonabeau, Marco Dorigo, and Guy Theraulaz",
    publisher: "Oxford University Press",
    year: "1999",
    price: "20.45",
    ISBN13: "9780195131581",
    details:
      "This book provides a detailed look at models of social insect behaviour and how to apply these models in the design of complex systems. The book shows how these models replace an emphasis on control, preprogramming, and centralization with designs featuring autonomy, emergence, and distributed functioning. These designs are proving immensely flexible and robust, able to adapt quickly to changing environments and to continue functioning even when individual elements fail. In particular, these designs are an exciting approach to the tremendous growth of complexity in software and information. Swarm Intelligence draws on up-to-date research from biology, neuroscience, artificial intelligence, robotics, operations research, and computer graphics, and each chapter is organized around a particular biological example, which is then used to develop an algorithm, a multiagent system, or a group of robots. The book will be an invaluable resource for a broad range of disciplines.",
    img: "/assets/book7.jpg",
  },
  {
    bookno: "8",
    name: "Data structures and algorithms in Java",
    author: "Michael T. Goodrich; Roberto Tamassia; Michael H. Goldwasser",
    publisher: "John Wiley & Sons",
    year: "2015",
    price: "45.38",
    ISBN13: "978-1118808573",
    details:
      "The design and analysis of efficient data structures has long been recognized as a key component of the Computer Science curriculum. Goodrich and Tomassia's approach to this classic topic is based on the object-oriented paradigm as the framework of choice for the design of data structures. For each ADT presented in the text, the authors provide an associated Java interface. Concrete data structures realizing the ADTs are provided as Java classes implementing the interfaces. The Java code implementing fundamental data structures in this book is organized in a single Java package, net.datastructures. This package forms a coherent library of data structures and algorithms in Java specifically designed for educational purposes in a way that is complimentary with the Java Collections Framework.",
    img: "/assets/book8.jpg",
  },
  {
    bookno: "9",
    name: "Analysis of algorithms: an active learning approach",
    author: "Jeffrey J. McConnell",
    publisher: "Jones and Bartlett Publishers",
    year: "2008",
    price: "15.23",
    ISBN13: "978-5948362168",
    details:
      "he two major goals of this book are to raise awareness of the impact that algorithms can have on the efficiency of a program and to develop the skills necessary to analyze any algorithms that are used in programs. In looking at many commercial products today, it appears that some software designers are unconcerned about space and time efficiency. If a program takes too much space, they expect that the user will buy more memory. If a program takes too long, they expect that the user will buy a faster computer.",
    img: "/assets/book9.jpg",
  },
  {
    bookno: "10",
    name: "Operating system concepts",
    author: "Abraham Silberschatz; Peter B. Galvin; Greg Gagne",
    publisher: "John Wiley & Sons",
    year: "2005",
    price: "20.89",
    ISBN13: "978-0471694663",
    details:
      "By staying current, remaining relevant, and adapting to emerging course needs, this market–leading text has continued to define the operating systems course. This Seventh Edition not only presents the latest and most relevant systems, it also digs deeper to uncover those fundamental concepts that have remained constant throughout the evolution of today’s operation systems. With this strong conceptual foundation in place, students can more easily understand the details related to specific systems.",
    img: "/assets/book10.jpg",
  },
  {
    bookno: "11",
    name: "Computer networking: a top-down approach",
    author: "James F. Kurose; Keith W. Ross",
    publisher: "Pearson",
    year: "2017",
    price: "30.49",
    ISBN13: " 978-1292153599",
    details:
      "The text works its way from theapplication layer down toward the physical layer, motivating students byexposing them to important concepts early in their study of networking.Focusing on the internet and the fundamentally important issues of networking,this text provides an excellent foundation for students in computer science andelectrical engineering, without requiring extensive knowledge of programming ormathematics.",
    img: "/assets/book11.jpg",
  },
  {
    bookno: "12",
    name: "Modern operating systems",
    author: "Andrew S. Tanenbaum; Herbert Bos",
    publisher: "Pearson Education",
    year: "2014",
    price: "50.24",
    ISBN13: "978-1292061429",
    details:
      "The widely anticipated revision of this worldwide best-seller incorporates the latest developments in operating systems (OS) technologies. The Fourth Edition includes up-to-date materials on relevant OS. Tanenbaum also provides information on current research based on his experience as an operating systems researcher.",
    img: "/assets/book12.jpg",
  },
  {
    bookno: "13",
    name: "Berserk Deluxe Volume 1",
    author: "Kentaro Miura",
    publisher: "Dark Horse Comics,U.S.",
    year: "2019",
    price: "29.99",
    ISBN13: "978-1506711980",
    details:
      "Kentaro Miura's Berserk has outraged, horrified, and delighted manga and anime fanatics since 1989, creating an international legion of hardcore devotees and inspiring a plethora of TV series, feature films, and video games. And now the badass champion of adult fantasy manga is presented in an oversized 7 deluxe hardcover edition, nearly 700 pages amassing the first three Berserk volumes, with following volumes to come to serve up the entire series in handsome bookshelf collections.",
    img: "https://i.ebayimg.com/images/g/fIQAAOSwXrleTkML/s-l640.jpg",
  },
  {
    bookno: "14",
    name: "HELLSING DELUXE VOLUME 3",
    author: "Andrew S. Tanenbaum, Herbert Bos",
    publisher: "Dark Horse Comics,U.S.",
    year: "2021",
    price: "29.16",
    ISBN13: "978-1506720029",
    details:
      "The curtain rises on the final act of the apocalyptic war between vampires, werewolves, fanatics, and mercenaries. Amidst the grisly wreckage that is now London, the champions of light and darkness face off in a final showdown that will determine the humanity’s future… or its downfall",
    img: "https://images-na.ssl-images-amazon.com/images/I/41mXm9mY2hL._SX348_BO1,204,203,200_.jpg",
  },
];
